# Generated by Django 4.2.8 on 2024-02-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detalle_horario',
            unique_together={('horario', 'espacioCurricular', 'dia', 'hora')},
        ),
    ]
