# Generated by Django 4.2.8 on 2024-01-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_horario',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.horario'),
            preserve_default=False,
        ),
    ]
