# Generated by Django 4.2.8 on 2024-02-04 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionestudianteciclo',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionestudianteciclo',
            unique_together={('estudiante', 'ciclo', 'anio')},
        ),
    ]
