# Generated by Django 4.1.4 on 2023-08-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='alumnos',
            field=models.ManyToManyField(to='Core.estudiante'),
        ),
    ]
