# Generated by Django 4.2.8 on 2024-02-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', to='Core.estudiante'),
        ),
    ]
