# Generated by Django 4.2.8 on 2024-01-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='estudiantes',
        ),
        migrations.AddField(
            model_name='aula',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='aulas_del_estudiante', to='Core.estudiante'),
        ),
    ]
