# Generated by Django 4.2.8 on 2024-06-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_calificacion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('instancia', 'ciclo', 'estudiante', 'espacioCurricular')},
        ),
    ]
