# Generated by Django 4.1.4 on 2023-08-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_division_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandeestudios',
            name='esActual',
            field=models.BooleanField(default=True),
        ),
    ]
