# Generated by Django 4.2.8 on 2024-03-07 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_detalle_horario_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Ej: 16/02/2024')),
                ('anio', models.ForeignKey(help_text='Ej: 1,año', on_delete=django.db.models.deletion.CASCADE, to='Core.anioplan')),
                ('ciclo', models.ForeignKey(help_text='Ej: Actual', null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.ciclo')),
                ('docente', models.ForeignKey(help_text='Ej: Juan Perez', null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.docente')),
            ],
            options={
                'unique_together': {('docente', 'ciclo')},
            },
        ),
    ]
