# Generated by Django 4.2.8 on 2024-01-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_detalle_horario_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandeestudios',
            name='implementado',
            field=models.BooleanField(default=False),
        ),
    ]
