# Generated by Django 4.1.4 on 2023-08-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_plandeestudios_esactual'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='esActual',
            field=models.BooleanField(default=True),
        ),
    ]
