# Generated by Django 4.2.8 on 2024-01-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_plandeestudios_implementado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='aula',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='aulas_del_estudiante', to='Core.estudiante'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='aulas',
            field=models.ManyToManyField(blank=True, related_name='estudiantes_en_aula', to='Core.aula'),
        ),
    ]
