# Generated by Django 4.2.8 on 2024-03-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_inscripciondocente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripciondocente',
            unique_together=set(),
        ),
    ]
