# Generated by Django 4.2.8 on 2024-04-13 14:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_inscripciondocente_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Nota Final', max_length=50)),
                ('disponible', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, help_text='Ej: 16/02/2024')),
                ('fecha_fin', models.DateField(help_text='Ej: 16/02/2024')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.ciclo')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='instancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docente', to='Core.instancia'),
        ),
    ]
