# Generated by Django 4.2.8 on 2024-05-04 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_calificacion_nota_instancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='ciclo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.ciclo'),
        ),
    ]
