# Generated by Django 4.2.8 on 2024-01-23 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inasistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=django.utils.timezone.now)),
                ('falta', models.BooleanField(default=True)),
                ('justificacion', models.CharField(max_length=50)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.estudiante')),
            ],
            options={
                'unique_together': {('dia', 'estudiante')},
            },
        ),
    ]
