# Generated by Django 4.2.8 on 2024-02-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        ('Clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inasistencias',
            name='ciclo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.ciclo'),
            preserve_default=False,
        ),
    ]
